### ISSUE TITLE
Store Indexed Rb not encoded

### ISSUE THREAD

**Issue by gregk27** [c-ola/minisrc-assembler#1]
Assembling a store instruction yields the same result with and without Rb

`python .\minisrc-asm.py -l "st 0x87, R1"`
yields
`st 0x87, R1          :  0x10800087`

`python .\minisrc-asm.py -l "st 0x87(R1), R1"`
yields
`st 0x87(R1), R1      :  0x10800087`

The second instruction should be closer to `0x10880087`

**Comment by c-ola** [comment]
Oh thanks for noticing that. It was a bug in the default configuration in file in `configs/default.py`, where the store text format didn't have the right identifier for parsing registers. 
Should be fixed now
![image](https://github.com/c-ola/minisrc-assembler/assets/59809814/e5cc3aec-003e-4e04-82a4-99bb2a0ac105)
